name: publichealth


channels:
  - conda-forge

dependencies:
  # Other items
  - jupyter-rsession-proxy==2.2.1
  - traitlets==5.14.3
  - appmode==1.0.0

  # pip installed packages, conda is preferred
  - pip:
      - rise==5.7.1
      - git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling
      - jupyter-tree-download==1.0.1
